spring.datasource.url=jdbc:postgresql://localhost:5436/banco_api
spring.datasource.username=postgres
spring.datasource.password=Maker@1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect